//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureLoginService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userinfo
    {
        public string UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string DOB { get; set; }
        public bool LockedStatus { get; set; }
        public string Role_id { get; set; }
        public string PwdHashSalt { get; set; }
    
        public virtual tbl_roles tbl_roles { get; set; }
    }
}
